DATALOADER:
  TRAIN:
    BATCH_SIZE: 128
  TEST:
    BATCH_SIZE: 64
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  # PIXEL_MEAN: [0.5, 0.5, 0.5]
  # PIXEL_STD: [0.5, 0.5, 0.5]
  # TRANSFORMS: ["normalize"]
  TRANSFORMS: ["normalize"]

OPTIM:
  NAME: "sgd"
  LR: 0.01
  MAX_EPOCH: 50
  LR_SCHEDULER: "Cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5

TRAIN:
  PRINT_FREQ: 5

MODEL:
  NAME: DAF
  DAF:
    BACKBONE: "resnet50"