PROMPT_TEMPLATES = {
    "OxfordPets": "a photo of a {}, a type of pet.",
    "OxfordFlowers": "a photo of a {}, a type of flower.",
    "FGVCAircraft": "a photo of a {}, a type of aircraft.",
    "DescribableTextures": "{} texture.",
    "EuroSAT": "a centered satellite photo of {}.",
    "StanfordCars": "a photo of a {}.",
    "Food101": "a photo of {}, a type of food.",
    "SUN397": "a photo of a {}.",
    "Caltech101": "a photo of a {}.",
    "UCF101": "a photo of a person doing {}.",
    "ImageNet": "a photo of a {}.",
    "ImageNetV2": "a photo of a {}.",
    "ImageNetR": "a photo of a {}.",
    "ImageNetSketch": "a photo of a {}.",
    "ImageNetA": "a photo of a {}.",
    "ObjectNet": "a photo of a {}.",
    "Digits": "a picture of a {}.",
    "PACS": "a picture of a {}.",
    "OfficeHome": "a picture of a {}.",
    "VLCS": "a picture of a {}.",
    "NICO": "a picture of a {}.",
    "DomainNet": "a picture of a {}.",
    "TerraInc": "a picture of a {}.",
}
